# Generated by Django 3.0.2 on 2020-01-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('C', 'Completed'), ('R', 'Reading'), ('W', 'WhishList')], max_length=1)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-due_date', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
    ]
