# Generated by Django 3.0.2 on 2020-01-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200111_0408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['due_date', 'name']},
        ),
    ]
