# Generated by Django 3.0.2 on 2020-01-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200112_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('link', models.URLField(max_length=300)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('h', 'high'), ('m', 'mid'), ('l', 'low')], max_length=1)),
            ],
            options={
                'verbose_name': 'Blog/Article',
                'verbose_name_plural': 'Blog/Articles',
                'ordering': ['due_date', 'title'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='priority',
            field=models.CharField(choices=[('h', 'high'), ('m', 'mid'), ('l', 'low')], default='mid', max_length=1),
        ),
    ]
