# Generated by Django 3.0.2 on 2020-01-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200112_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='priority',
            field=models.CharField(choices=[('h', 'high'), ('m', 'mid'), ('l', 'low')], max_length=1),
        ),
    ]
