# Generated by Django 3.0.2 on 2020-01-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200112_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('R', 'Reading'), ('W', 'WhishList')], max_length=1),
        ),
    ]
