# Generated by Django 3.0.2 on 2020-01-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200112_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='read_online',
            field=models.URLField(blank=True, default='', max_length=300, null=True),
        ),
    ]
