# Generated by Django 3.0.2 on 2020-01-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_read_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='read_online',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
